version: "3.8"

services:
  wise-database:
    image: postgres:12
    ports:
      - 5001:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prisma
  wise-server:
    image: shafiqnazrin/centos-apache:0.0.1
    ports:
      - 80:80
volumes:
  pgdata:
