version: "3.8"

services:
  database:
    image: postgres:12
    ports:
      - 5001:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prisma
  server:
    image:
volumes:
  pgdata:
